<Project InitialTargets="Soup;Compile" ToolsVersion="17.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Set the repository root into a variable -->
  <PropertyGroup>
    <SourceRoot>$(MSBuildThisFileDirectory)</SourceRoot>
    <DefineConstants>$(DefineConstants);IDE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0"
                      Condition="'$(MsBuildProjectName)' == 'Scripts'" />
  </ItemGroup>

  <PropertyGroup Condition="$(RootNamespace.StartsWith('Mods.'))">
    <RootNamespace>$(RootNamespace.Replace('Mods.', ''))</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="$(RootNamespace.Contains('.Scripts'))">
    <RootNamespace>$(RootNamespace.Replace('.Scripts', ''))</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(MsBuildProjectName)' == 'MoreCommandsMod'">
    <None Include="$(SourceRoot)Assets\Mods\MoreCommands\.editorconfig" Link="Assets\Mods\MoreCommands\.editorconfig" />
    <EditorConfig Include="$(SolutionDir)Assets\Mods\MoreCommands\.editorconfig" />
  </ItemGroup>

  <ItemGroup Condition="'$(MsBuildProjectName)' == 'UnityExplorer'">
    <None Include="$(SourceRoot)Assets\Mods\UnityExplorer\.editorconfig" Link="Assets\Mods\UnityExplorer\.editorconfig" />
    <EditorConfig Include="$(SourceRoot)Assets\Mods\UnityExplorer\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <LibraryProjects Include="Assembly-CSharp-Editor-firstpass" />
    <LibraryProjects Include="CoreLib" />
    <LibraryProjects Include="CoreLib.Audio" />
    <LibraryProjects Include="CoreLib.Commands" />
    <LibraryProjects Include="CoreLib.Drops" />
    <LibraryProjects Include="CoreLib.Editor" />
    <LibraryProjects Include="CoreLib.Entity" />
    <LibraryProjects Include="CoreLib.Equipment" />
    <LibraryProjects Include="CoreLib.JsonLoader" />
    <LibraryProjects Include="CoreLib.Localization" />
    <LibraryProjects Include="CoreLib.ModderTools" />
    <LibraryProjects Include="CoreLib.Resources" />
    <LibraryProjects Include="CoreLib.RewiredExtension" />
    <LibraryProjects Include="CoreLib.Tilesets" />
    <LibraryProjects Include="CoreLib.UserInterface" />
    <LibraryProjects Include="Mischief.MDV.Editor" />
    <LibraryProjects Include="ModSDK.Editor" />
    <LibraryProjects Include="PPv2URPConverters" />
    <LibraryProjects Include="PugMod.Importer" />
    <LibraryProjects Include="PugMod.SDK" />
    <LibraryProjects Include="SDKExtensions" />
    <LibraryProjects Include="Unity.2D.Sprite.Editor" />
    <LibraryProjects Include="Unity.Physics.Custom" />
    <LibraryProjects Include="Unity.Physics.Custom.Editor" />
    <LibraryProjects Include="Unity.RenderPipeline.Universal.ShaderLibrary" />
    <LibraryProjects Include="Unity.RenderPipelines.Core.Editor" />
    <LibraryProjects Include="Unity.RenderPipelines.Core.Runtime" />
    <LibraryProjects Include="Unity.RenderPipelines.Core.ShaderLibrary" />
    <LibraryProjects Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary" />
    <LibraryProjects Include="Unity.RenderPipelines.Universal.Editor" />
    <LibraryProjects Include="Unity.RenderPipelines.Universal.Runtime" />
    <LibraryProjects Include="Unity.RenderPipelines.Universal.Shaders" />
    <LibraryProjects Include="Unity.ShaderGraph.Editor" />
    <LibraryProjects Include="Unity.ShaderGraph.Utilities" />
    <LibraryProjects Include="UnityEditor.UI" />
    <LibraryProjects Include="UnityEngine.UI" />
  </ItemGroup>

  <UsingTask TaskName="JoinString" TaskFactory="CodeTaskFactory"
             AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <Value ParameterType="System.String[]" Required="true" />
      <Seperator ParameterType="System.String" Output="true" />
      <Result ParameterType="System.String" Output="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
            Result = string.Join(Seperator, Value);
            ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="Soup">
    <JoinString Value="@(LibraryProjects->'%(Identity)')" Seperator="', '">
      <Output PropertyName="Result" TaskParameter="Result" />
    </JoinString>
    <Message Text="LibraryProjects->'%25;(Identity)' = [ '$(Result1)' ]" Importance="High" />
    <JoinString Value="%(LibraryProjects.Identity)" Seperator="', '">
      <Output PropertyName="Result" TaskParameter="Result" />
    </JoinString>
    <Message Text="LibraryProjects.Identity  = [ '$(Result2)' ]" Importance="High" />
    <JoinString Value="@(LibraryProjects)" Seperator="', '">
      <Output PropertyName="Result" TaskParameter="Result" />
    </JoinString>
    <Message Text="LibraryProjects = [ '$(Result3)' ]" Importance="High" />
    <Message Text="MSBuildProjectName = '$(MSBuildProjectName)'" Importance="High" />
    <Message Text="RootNamespace = '$(RootNamespace)'" Importance="High" />
  </Target>

  <ItemGroup Condition="'@(LibraryProjects->'%(Identity)')' == '$(MSBuildProjectName)'">
    <None Include="$(SourceRoot)Library\.editorconfig" Link=".editorconfig" />
    <EditorConfig Include="$(SourceRoot)Library\.editorconfig" />
  </ItemGroup>
</Project>